language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master
    - dev

before_install:
  - pip install $DJANGO
  # TODO: remove when openwisp-utils with isort 5 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]
  - pip install -U https://github.com/openwisp/netdiff/tarball/dev
  # needed to test integrations
  - pip install -U https://github.com/openwisp/openwisp-controller/tarball/master
  - pip install -U https://github.com/openwisp/openwisp-monitoring/tarball/trigger-device-checks-improvement
  - pip install -U --no-deps https://github.com/openwisp/openwisp-notifications/tarball/master

install:
  - python setup.py -q develop
  - pip install -r requirements-test.txt

script:
  - coverage run --source=openwisp_network_topology runtests.py
  - ./run-qa-checks
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
